AllCops:
  TargetRubyVersion: 2.4
  NewCops: enable

Style/GlobalVars:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Security/Eval:
  Enabled: false

Layout/LineLength:
  Max: 90
