service: serverless-rack-test

provider:
  name: aws
  runtime: ruby2.5
  region: us-east-1
  stage: dev
  environment:
    STAGE: ${self:custom.stage}

package:
  exclude:
    - node_modules/**
    # - Gemfile
    # - Gemfile.lock

functions:
  app:
    handler: rack_adapter.handler
    events:
      - http: ANY /
      - http: ANY {proxy+}

custom:
  stage: ${opt:stage, self:provider.stage}
